### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by CityAceE** [kumaashi/RaspberryPI#2]
https://github.com/kumaashi/RaspberryPI/blob/ee5ecbaa68635a4c577c00ec8ec1e4e0f8ee815e/RPIZEROW/Sample_HDMI_DMA_Audio_03/main.c#L130

I can be wrong, but it looks like you forgot OR operation:

```
	mai_ctl |= (1 << 0);  //RST
	mai_ctl |= (1 << 2);  //UF
	mai_ctl |= (1 << 9);  //FLUSH
```

**Comment by kumaashi** [comment]
Thanks for the information. I think the point is whether this register setting has to be done all at once. I don't know if this is correct, but since the following source is the only “correct” one, I'm thinking that I should probably or and write them all at once.

https://github.com/raspberrypi/linux/blob/ba0f2212e0e100ee16bdde76b7efca6bb8ee9446/drivers/gpu/drm/vc4/vc4_hdmi.c#L2497

**Comment by kumaashi** [comment]
I have’t a environment of rpi2 now so could you confirm your side or create a pull request?

**Comment by kumaashi** [comment]
I remember so I was align as following linux kernel code to mimic so current main branch is too old.

https://patchwork.kernel.org/project/linux-arm-kernel/patch/20170207210703.7082-2-eric@anholt.net/

If it does not work without ORing, would you apply to OR?
The prerequisite environment for this repository is RPI ZERO W.

**Comment by kumaashi** [comment]
memo : I will buy rpi series for future I rethink this issue...
